// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cSSLB
SEXP cSSLB(SEXP Y_SEXP, SEXP B_init, SEXP sigmas_init, SEXP Tau_init, SEXP thetas_init, SEXP theta_tildes_init, SEXP nus_init, SEXP lambda1_SEXP, SEXP lambda0s_SEXP, SEXP lambda1_tilde_SEXP, SEXP lambda0_tildes_SEXP, SEXP a_SEXP, SEXP b_SEXP, SEXP a_tilde_SEXP, SEXP b_tilde_SEXP, SEXP alpha_SEXP, SEXP d_SEXP, SEXP eta_SEXP, SEXP xi_SEXP, SEXP sigma_min_SEXP, SEXP IBP_SEXP, SEXP EPSILON_SEXP, SEXP MAX_ITER_SEXP);
RcppExport SEXP _SSLB_cSSLB(SEXP Y_SEXPSEXP, SEXP B_initSEXP, SEXP sigmas_initSEXP, SEXP Tau_initSEXP, SEXP thetas_initSEXP, SEXP theta_tildes_initSEXP, SEXP nus_initSEXP, SEXP lambda1_SEXPSEXP, SEXP lambda0s_SEXPSEXP, SEXP lambda1_tilde_SEXPSEXP, SEXP lambda0_tildes_SEXPSEXP, SEXP a_SEXPSEXP, SEXP b_SEXPSEXP, SEXP a_tilde_SEXPSEXP, SEXP b_tilde_SEXPSEXP, SEXP alpha_SEXPSEXP, SEXP d_SEXPSEXP, SEXP eta_SEXPSEXP, SEXP xi_SEXPSEXP, SEXP sigma_min_SEXPSEXP, SEXP IBP_SEXPSEXP, SEXP EPSILON_SEXPSEXP, SEXP MAX_ITER_SEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Y_SEXP(Y_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type B_init(B_initSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sigmas_init(sigmas_initSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Tau_init(Tau_initSEXP);
    Rcpp::traits::input_parameter< SEXP >::type thetas_init(thetas_initSEXP);
    Rcpp::traits::input_parameter< SEXP >::type theta_tildes_init(theta_tildes_initSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nus_init(nus_initSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lambda1_SEXP(lambda1_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lambda0s_SEXP(lambda0s_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lambda1_tilde_SEXP(lambda1_tilde_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lambda0_tildes_SEXP(lambda0_tildes_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type a_SEXP(a_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b_SEXP(b_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type a_tilde_SEXP(a_tilde_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b_tilde_SEXP(b_tilde_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type alpha_SEXP(alpha_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type d_SEXP(d_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type eta_SEXP(eta_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type xi_SEXP(xi_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sigma_min_SEXP(sigma_min_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type IBP_SEXP(IBP_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type EPSILON_SEXP(EPSILON_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type MAX_ITER_SEXP(MAX_ITER_SEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(cSSLB(Y_SEXP, B_init, sigmas_init, Tau_init, thetas_init, theta_tildes_init, nus_init, lambda1_SEXP, lambda0s_SEXP, lambda1_tilde_SEXP, lambda0_tildes_SEXP, a_SEXP, b_SEXP, a_tilde_SEXP, b_tilde_SEXP, alpha_SEXP, d_SEXP, eta_SEXP, xi_SEXP, sigma_min_SEXP, IBP_SEXP, EPSILON_SEXP, MAX_ITER_SEXP));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SSLB_cSSLB", (DL_FUNC) &_SSLB_cSSLB, 23},
    {NULL, NULL, 0}
};

RcppExport void R_init_SSLB(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
