# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.cSSLB <- function(Y_SEXP, B_init, sigmas_init, Tau_init, thetas_init, theta_tildes_init, nus_init, lambda1_SEXP, lambda0s_SEXP, lambda1_tilde_SEXP, lambda0_tildes_SEXP, a_SEXP, b_SEXP, a_tilde_SEXP, b_tilde_SEXP, alpha_SEXP, d_SEXP, eta_SEXP, xi_SEXP, sigma_min_SEXP, IBP_SEXP, EPSILON_SEXP, MAX_ITER_SEXP) {
    .Call(`_SSLB_cSSLB`, Y_SEXP, B_init, sigmas_init, Tau_init, thetas_init, theta_tildes_init, nus_init, lambda1_SEXP, lambda0s_SEXP, lambda1_tilde_SEXP, lambda0_tildes_SEXP, a_SEXP, b_SEXP, a_tilde_SEXP, b_tilde_SEXP, alpha_SEXP, d_SEXP, eta_SEXP, xi_SEXP, sigma_min_SEXP, IBP_SEXP, EPSILON_SEXP, MAX_ITER_SEXP)
}

